services:
  db: 
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s

  config-server:
    container_name: config-server
    build:
      context: ConfigServer
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - ConfigServer/.env
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  eureka-server:
    container_name: eureka-server
    build:
      context: EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    env_file:
      - EurekaServer/.env
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  api-gateway:
    container_name: api-gateway
    build:
      context: APIGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    env_file:
      - APIGateway/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/actuator/health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  user-service:
    container_name: user-service
    build:
      context: UserService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    env_file:
      - UserService/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - backend
      - backend-database
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  product-service:
    container_name: product-service
    build:
      context: ProductService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    env_file:
      - ProductService/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - backend-database
      - backend
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  order-service:
    container_name: order-service
    build:
      context: OrderService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    env_file:
      - OrderService/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - backend
      - backend-database
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

volumes:
  pgdata:

networks:
  backend-database:
  backend: