server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: eureka-server
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  config:
    import: ${SPRING_CONFIG_IMPORT}
management:
  endpoints:
    web:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS}
        allowed-methods: GET
        allowed-headers: "*"