server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          default-label: ${GITHUB_DEFAULT_BRANCH:main}
          username: ${GITHUB_AUTH_USERNAME}
          password: ${GITHUB_AUTH_PASSWORD_TOKEN}
          force-pull: true
          clone-on-start: ${SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START:false}
          search-paths: ${SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS:Backend/CloudConfig}

management:
  endpoints:
    web:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
        allowed-methods: GET
        allowed-headers: "*"