spring:
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: ${SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL:2000}
        max-attempts: ${SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS:5}
app:
  cookie:
    refreshToken:
      path: /api
      expiration: ${APP_COOKIE_REFRESH_TOKEN_EXPIRATION:259200}
    accessToken:
      path: /
      expiration: ${APP_COOKIE_ACCESS_TOKEN_EXPIRATION:3600}
  applicationSignatureKey: ${APP_APPLICATIONSIGNATUREKEY}
  jwt:
    issuer: api.obsidian.com
    audience: obsidian.com
    refreshTokenExpiration: 259200
    accessTokenExpiration: 3600
  gateway:
    secret: ${APP_GATEWAY_SECRET}
  service:
    secret: ${APP_SERVICE_SECRET}
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 45000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true