spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: false
    show-sql: false
app:
  frontend:
    url: ${APP_FRONTEND_URL}
  cors:
    enabled: ${APP_CORS_ENABLED:false}
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
logging:
  level:
    com:
      Ecommerce:
        OrderService: WARN