spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: false
    show-sql: false
app:
  frontend:
    url: ${APP_FRONTEND_URL}
  cors:
    enabled: true
    allowed-origins: ${APP_CORS_ALLOWED_ORIGIN}
  cookie:
    secure: true
    sameSite: None
logging:
  level:
    com:
      Ecommerce:
        UserService: WARN