server:
  forward-headers-strategy: FRAMEWORK
  port: ${SERVER_PORT:8080}
app:
  cors:
    allowed-methods: ${APP_CORS_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
    allowed-headers: ${APP_CORS_ALLOWED_HEADERS:Authorization,Content-Type,Accept,X-Requested-With,Cache-Control}
    exposed-headers: ${APP_CORS_EXPOSED_HEADERS:Authorization,Access-Control-Allow-Origin,Access-Control-Allow-Credentials}
    allow-credentials: ${APP_CORS_CREDENTIALS:true}
    max-age: ${APP_CORS_MAX_AGE:3600}

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}/${SPRING_DATASOURCE_DB}?sslmode=require&channel_binding=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      max-lifetime: 300000
      keepalive-time: 60000
      idle-timeout: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: ${GOOGLE_REDIRECT_URI}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
sentry:
  dsn: https://e8f5a511d7dbb4973f50ffbc594ff5a7@o4511749183045632.ingest.de.sentry.io/4511749185798224
  send-default-pii: true