spring:
  application:
    name: product-service
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
management:
  endpoints:
    web:
      cors:
        allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
        allowed-methods: GET
        allowed-headers: "*"