name: Workflow to Deploy the Ecommerce Backend on every push commit to the docker hub.
on:
  push:
permissions:
  contents: read

jobs:
  test-build-push:
    name: Test the application, Build it and Push the docker image to docker hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          include:
          - service: config-server
            path: ./ConfigServer
          - service: eureka-server
            path: ./EurekaServer
          - service: api-gateway
            path: ./APIGateway
          - service: user-service
            path: ./UserService
          - service: product-service
            path: ./ProductService
          - service: order-service
            path: ./OrderService

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Run Tests
        run: cd ${{ matrix.path }} && mvn verify -Dtest.groups=integration

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build the images
        run: docker build -t bipinkoirala/${{ matrix.service }}:latest ${{ matrix.path }}

      - name: Push the images to Docker Hub
        run: docker push bipinkoirala/${{ matrix.service }}:latest